//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinkerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Values
    {
        public int idMeasures { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int Sensoren_idSensoren { get; set; }
        public int Sensoren_Devices_idDevices { get; set; }
    
        public virtual Sensors Sensors { get; set; }
    }
}
